storage:
  # Where to store all the data
  storage_path: ./storage

  performance:
    # Number of parallel threads used for search operations. If 0 - auto selection.
    max_search_threads: 4

  optimizers:

    # If the number of segments exceeds this value, the optimizer will merge the smallest segments.
    max_segment_number: 4

    # Maximum number of vectors to store in-memory per segment.
    # Segments larger than this threshold will be stored as read-only memmaped file.
    #
    # Don't use memmap for this benchmark
    memmap_threshold: 500000000

    # Maximum number of vectors allowed for plain index.
    # Default value based on https://github.com/google-research/google-research/blob/master/scann/docs/algorithms.md
    #
    # For performance optimization: index is disabled before all points are loaded
    indexing_threshold: 500000000

    # Starting from this amount of vectors per-segment the engine will start building index for payload.
    #
    # Payload if not used in this benchmark
    payload_indexing_threshold: 500000000

    # Minimum interval between forced flushes.
    flush_interval_sec: 10

  # Default parameters of HNSW Index. Could be override for each collection individually
  hnsw_index:
    # Number of edges per node in the index graph. Larger the value - more accurate the search, more space required.
    m: 16
    # Number of neighbours to consider during the index building. Larger the value - more accurate the search, more time required to build index.
    ef_construct: 100
    # Minimal amount of points for additional payload-based indexing.
    # If payload chunk is smaller than `full_scan_threshold` additional indexing won't be used -
    # in this case full-scan search should be preferred by query planner and additional indexing is not required.
    full_scan_threshold: 10000
